### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by d235j**
This completely fixes Travis build.

I removed Clang from Linux builds; I can put it back if you'd like. Also if you want I can squash these commits — but it did involve a lot of testing.

### CODE REVIEW

**Comment by rpavlik** [comment]
Wait, you needed OpenCV for steamvr-osvr? Couldn't you just do a client-only build of core and disable BUILD_WITH_OPENCV?

Now, I would appreciate the same on the main osvr-core, since there the lack of a modern OpenCV is actually a pain.

Looks reasonable to me, though I suppose I should probably let somebody else do the merge ( @JeroMiya  ?) since I'm not really in the steamvr loop these days much. Any particular reason to remove clang? I like to keep it around because it keeps me honest, and keeps the error messages readable.

**Comment by rpavlik** [comment]
(PS. Sorry, that comment was a little harsh. Thanks for the hard work, I can see it was a lot of work!)

**Comment by toxicFork** [comment]
In my cmake configuration it said opencv not found but it would still build
(the dll), what piece is OpenCV used for, in osvr/steamvr ?

**Comment by d235j** [comment]
@rpavlik I suppose if you'd prefer a client-only build here I can do that after this gets merged into OSVR-Core.

As I said I can put Clang back if so desired — just easier to test with 4 instead of 6 build variants running.

**Pull request merged**
