### PR TITLE
Use submodule for SteamVR dependencies

### PR DESCRIPTION
**Pull request by d235j**
This switches to using a submodule for the SteamVR/OpenVR headers and libraries. If you want to make a private fork of that repo and use that instead, feel free to make the needed changes.

### CODE REVIEW

**Comment by JeroMiya** [comment]
Could you update the readme please? Just a quick note to checkout out the submodule before running cmake. Currently it says to clone OpenVR separately. Thanks!

**Comment by d235j** [comment]
I've done so. Is this sufficient?

**Comment by rpavlik** [comment]
It was initially written against an early public Steamworks VR release before they called it "OpenVR", then was partially updated to at least build against a private copy of the "OpenVR" driver headers (roughly 1 year newer of API, so this is probably where the missing functionality snuck in), then modified to build with the public version of the "OpenVR" and updated minimally since then. I know one of the early versions got closer to working, but I believe you are correct that it is missing some chunks of functionality.

**Comment by d235j** [comment]
I see. Well, right now I'm fighting with some hidapi bug anyway, so I have to figure that out first.

**Pull request merged**
