### PR TITLE
Steamvr 0.9.14 support

### PR DESCRIPTION
**Pull request by d235j**
Uncertain whether this actually works — SteamVR has not been very cooperative lately.

### CODE REVIEW

**Comment by JeroMiya** [comment]
Well, it doesn't appear to have made things worse. The HMD indicator in the server UI is green now for me, which is an improvement? My problem is that I can't get the compositor window to open in the HMD. Instead it opens on the primary display. Also the compositor window seems messed up somehow. One eye is a flip of the other (horizontally), and I remember it used to be a sphere, where now it looks like two planes with a grid of lines on them. Maybe a squashed sphere?

**Comment by toxicFork** [comment]
same exact issues here @JeroMiya.

**Comment by typhoidcoma** [comment]
Yeah same here... Def progress though!

**Comment by JeroMiya** [comment]
Aha! fixed the compositor window issue for me (kind of a hack, only works if your monitor is 1080p):

https://github.com/OSVR/SteamVR-OSVR/commit/7d991fd7eed9d2298ab318557d1d57ff3f75c4a3

I filed an issue about the tracking/projection issue:

https://github.com/OSVR/SteamVR-OSVR/issues/22

**Comment by d235j** [comment]
Lack of documentation strikes again! 
openvr_driver.h documents GetWindowBounds as returning "Size and position that the window needs to be on the VR display".

I also wonder how this will affect Direct Mode.

**Pull request merged**
