### PR TITLE
Fix build with OpenVR 0.9.9 and Mac build

### PR DESCRIPTION
**Pull request by d235j**
This fixes build; I have no idea whether it works though. Additionally, my implementation of GetMCImage is probably wrong — I'm not sure what it should be, as it does not seem to be documented. But it compiles!

### CODE REVIEW

**Comment by rpavlik** [comment]
I have no idea what it is either. @yboger do you know who we can ask what the 'MC' image is?

**Comment by rpavlik** [comment]
I'm guessing, since those are all pointers to ints, that those are all output parameters, so my hunch is that this will crash, but not sure.

**Comment by d235j** [comment]
A few minutes with a disassembler indicates that both the null driver and the oculus driver return a hardcoded 0 for this function, and do nothing else otherwise. Should I do the same here?

**Comment by rpavlik** [comment]
Ah, that sounds like a good plan to me, much better than dereferencing unknown pointers.

**Comment by d235j** [comment]
Yeah, good point. Will update in a few moments.

**Comment by d235j** [comment]
Updated; please review when you get a chance.

**Comment by d235j** [comment]
Of course, Valve just released 0.9.10 which breaks more things... Time for more updates.

**Comment by rpavlik** [comment]
This confirms my opinion that we should be using that repo as a submodule (forking first for safety) - they don't appear to have sufficient testing to keep master in a good state

**Comment by d235j** [comment]
It seems they added some camera related API, which the Oculus driver does not use (returning 0 or NULL for all function calls), but they screwed up and missed including a few typedefs. I opened https://github.com/ValveSoftware/openvr/issues/28 but I'll probably implement a workaround for now.

**Comment by rpavlik** [comment]
Merging this as-is though, so we at least get support through the previous version. Thanks!

**Comment by d235j** [comment]
I already have it compiling for 0.9.10; I'll submit a PR right now. I'm working on getting this testable on OS X.

**Pull request merged**
